akka {
  actor {
    default-dispatcher {
      type = Dispatcher
      executor = fork-join-executor
      throughput = 100
    }

    tournament-dispatcher {
      type = Dispatcher
      executor = fork-join-executor
      throughput = 50
      fork-join-executor {
        parallelism-min = 2
        parallelism-factor = 2.0
        parallelism-max = 8
      }
    }
  }
}
